name: "Docker Build"

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get version from commit (tag or SHA)
        id: getSemver
        run: |
          # Attempt to retrieve the most recent tag; fallback to a short commit hash if no tag exists.
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "$(echo ${GITHUB_SHA} | cut -c1-7)")
          echo "VERSION=${VERSION}"
          echo "::set-output name=semver::${VERSION}"
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: |
            techblog/whatsapp-media-vault
            techblog/whatsapp-media-vault:${{ steps.getSemver.outputs.semver }}
